name-template: 'v$RESOLVED_VERSION 🌈 👩‍🏫'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: '💄 Frontend'
    labels:
      - 'frontend'
  - title: '⚗️ Backend'
    labels:
      - 'backend'
  - title: '🐛 Bug Fixes'
    labels:
      - 'bug'
  - title: '⛴ Misc.'
    labels:
      - 'features'
      - 'enhancement'
  - title: '🌱 DevOps'
    label: 'devops'
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch

template: |
  ## Just Released:

  $CHANGES
