name: Deploy Frontend Prod

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  vercel-deploy:
    runs-on: ubuntu-latest
    env:
      VERCEL_TOKEN: ${{secrets.VERCEL_TOKEN}}
      VERCEL_ORG_ID: ${{secrets.VERCEL_ORG_ID}}
      VERCEL_PROJECT_ID: ${{secrets.PROJECT_ID}}

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Vercel Production Deploy
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID}}
          vercel-project-id: ${{ secrets.PROJECT_ID}}
          scope: ${{ secrets.VERCEL_SCOPE }}
          vercel-args: "--prod"
